"""add_balance_after_to_scheduled_post

Revision ID: 5498457c8c0f
Revises: b31205db45c4
Create Date: 2025-07-17 14:21:58.052113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5498457c8c0f'
down_revision: Union[str, None] = 'b31205db45c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_posts', sa.Column('balance_after', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('telegram_user_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('send_report_to', sa.String(), nullable=True))
    op.add_column('users', sa.Column('VIP_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'vip_level')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('vip_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'VIP_level')
    op.drop_column('users', 'send_report_to')
    op.drop_column('users', 'telegram_user_name')
    op.drop_column('users', 'telegram_id')
    op.drop_column('scheduled_posts', 'balance_after')
    # ### end Alembic commands ###
