"""update_channel_pair_columns_to_string

Revision ID: aa2cabe48113
Revises: 8a61c46768a5
Create Date: 2025-05-30 11:54:32.122439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2cabe48113'
down_revision: Union[str, None] = '8a61c46768a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_pairs', 'source_channel',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('channel_pairs', 'target_channel',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_pairs', 'target_channel',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('channel_pairs', 'source_channel',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
