"""add_username_to_users

Revision ID: b31205db45c4
Revises: b38f777aca2e
Create Date: 2025-07-08 03:18:24.336984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b31205db45c4'
down_revision: Union[str, None] = 'b38f777aca2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('vip_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'VIP_level')
    op.drop_column('users', 'send_report_to')
    op.drop_column('users', 'telegram_user_name')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegram_user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('send_report_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('VIP_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'vip_level')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
