"""initial_migration

Revision ID: d6fccac46a81
Revises: 
Create Date: 2025-04-28 00:12:15.060779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fccac46a81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               postgresql_using="telegram_id::bigint",  # Add explicit cast
               existing_nullable=True)
    op.drop_column('users', 'password_hash')
    op.add_column('workers', sa.Column('pid', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'workers', ['user_id'])
    op.create_unique_constraint('uq_telegram_sessions_path', 'telegram_sessions', ['session_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='unique')
    op.drop_column('workers', 'pid')
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'telegram_sessions', type_='unique')
    # ### end Alembic commands ###
