"""add_language_code_to_users

Revision ID: e8fc55773acd
Revises: fcfc4d7d3173
Create Date: 2025-09-12 18:04:51.080968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fc55773acd'
down_revision: Union[str, None] = 'fcfc4d7d3173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add language_code column to users table
    op.add_column('users', sa.Column('language_code', sa.String(), nullable=True, server_default='en'))
    
    op.drop_index('idx_channel_processing_state_channel_pair_id', table_name='channel_processing_state')
    op.drop_index('idx_channel_processing_state_updated_at', table_name='channel_processing_state')
    op.drop_index('idx_channel_processing_state_user_id', table_name='channel_processing_state')
    op.create_index(op.f('ix_channel_processing_state_id'), 'channel_processing_state', ['id'], unique=False)
    op.drop_constraint('channel_processing_state_channel_pair_id_fkey', 'channel_processing_state', type_='foreignkey')
    op.drop_constraint('channel_processing_state_user_id_fkey', 'channel_processing_state', type_='foreignkey')
    op.create_foreign_key(None, 'channel_processing_state', 'channel_pairs', ['channel_pair_id'], ['id'])
    op.create_foreign_key(None, 'channel_processing_state', 'users', ['user_id'], ['id'])
    op.drop_index('idx_users_is_newcomer', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_is_newcomer', 'users', ['is_newcomer'], unique=False)
    op.drop_constraint(None, 'channel_processing_state', type_='foreignkey')
    op.drop_constraint(None, 'channel_processing_state', type_='foreignkey')
    op.create_foreign_key('channel_processing_state_user_id_fkey', 'channel_processing_state', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('channel_processing_state_channel_pair_id_fkey', 'channel_processing_state', 'channel_pairs', ['channel_pair_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_channel_processing_state_id'), table_name='channel_processing_state')
    op.create_index('idx_channel_processing_state_user_id', 'channel_processing_state', ['user_id'], unique=False)
    op.create_index('idx_channel_processing_state_updated_at', 'channel_processing_state', ['updated_at'], unique=False)
    op.create_index('idx_channel_processing_state_channel_pair_id', 'channel_processing_state', ['channel_pair_id'], unique=False)
    
    # Remove language_code column from users table
    op.drop_column('users', 'language_code')
    # ### end Alembic commands ###
